version: '3.9'

services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
      - /var/www/app/vendor
    environment:
      - DB_HOST=hyperf-skeleton-mariadb
      - DB_PORT=3306
      - DB_DATABASE=hyperf-skeleton
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - AUTHORIZATION_API_BASE_URL=https://run.mocky.io/v3/
      - NOTIFICATION_API_BASE_URL=https://run.mocky.io/v3/
    ports:
      - 9501:9501
    command: |
      php /var/www/app/bin/hyperf.php server:watch
    depends_on:
      - hyperf-skeleton-mariadb
      - hyperf-skeleton-redis

  hyperf-skeleton-mariadb:
    container_name: hyperf-skeleton-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf-skeleton"

  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
    name: hyperf-network
