version: '3.9'

services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.2-alpine-v3.18-swoole-v5.0
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    depends_on:
      - hyperf-skeleton-mariadb
      - hyperf-skeleton-redis

  hyperf-skeleton-mariadb:
    container_name: hyperf-skeleton-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf-skeleton"

  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    ports:
      - 6379:6379  
#   image:
#     container_name: hyperf-skeleton
#     image: hyperf-skeleton
#     build:
#       context: .

#   bin:
#     container_name: bin.hyperf-skeleton
#     image: hyperf-skeleton
#     depends_on:
#       - image
#     entrypoint:
#       - php
#       - bin/hyperf.php
#     env_file:
#       - .env
#     volumes:
#       - ./:/opt/www

#   composer:
#     container_name: composer.hyperf-skeleton
#     image: hyperf-skeleton
#     entrypoint:
#       - composer
#     command: validate

#   app:
#     container_name: app.hyperf-skeleton
#     image: hyperf-skeleton
#     entrypoint:
#       - php
#       - bin/hyperf.php
#       - server:watch
#     ports:
#       - "9501:9501"

#   db:
#     container_name: db
#     image: mysql:8.1
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql.root.dev:/var/lib/mysql

#   cache:
#     container_name: cache
#     image: 'redis:6.2.6'

# volumes:
#   mysql.root.dev:
#     driver: local